# intent.toml

# [project]
# name = "demo"

[python]
version = "3.5l"

[commands]
test = "pytest -q"
lint = "ruff check ."

# [ci]
# commands = ["test", "lint"]

# [justfile]
# enable = true

[ci]
install = "-e .[dev]"

# we can do later
#[ci]
#install = ["pip install -e .[dev]", "pip install nodejs"]
#extras = ["dev", "lint"]